package com.gui.Leave;

import com.motorph.model.Employee;
import com.motorph.model.LeaveRequest;
import com.motorph.service.LeaveService;
import com.motorph.util.AppContext;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 * NetBeans GUI Builder form that lets an employee submit a leave request.
 *
 * Layout: defined in {@code LeaveRequestForm.form} (do not edit the generated
 * code section).  All business logic lives in the event handlers and helper
 * methods below.
 */
public class LeaveRequestForm extends javax.swing.JFrame {

    private final Employee currentEmployee;
    private final LeaveService leaveService;

    // ── Constructors ─────────────────────────────────────────────────────────

    /** Production constructor — receives the logged-in employee via AppContext. */
    public LeaveRequestForm() {
        this(AppContext.getInstance().getCurrentEmployee());
    }

    /** Parameterised constructor for explicit employee injection. */
    public LeaveRequestForm(Employee employee) {
        this.currentEmployee = employee;
        this.leaveService    = AppContext.getInstance().getLeaveService();
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        if (currentEmployee != null) {
            setTitle("Submit Leave Request — " + currentEmployee.getFullName());
        }
    }

    // ── Generated Code ───────────────────────────────────────────────────────

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelFrom = new javax.swing.JLabel();
        jTextFieldFrom = new javax.swing.JTextField();
        jLabelTo = new javax.swing.JLabel();
        jTextFieldTo = new javax.swing.JTextField();
        jLabelReason = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaReason = new javax.swing.JTextArea();
        jButtonSubmit = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jLabelHint = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Submit Leave Request");
        getContentPane().setLayout(null);

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitle.setText("Submit Leave Request");
        getContentPane().add(jLabelTitle);
        jLabelTitle.setBounds(20, 15, 280, 30);

        jLabelFrom.setText("From Date:");
        getContentPane().add(jLabelFrom);
        jLabelFrom.setBounds(20, 60, 80, 16);

        jTextFieldFrom.setToolTipText("yyyy-MM-dd");
        getContentPane().add(jTextFieldFrom);
        jTextFieldFrom.setBounds(110, 57, 150, 26);

        jLabelTo.setText("To Date:");
        getContentPane().add(jLabelTo);
        jLabelTo.setBounds(20, 100, 80, 16);

        jTextFieldTo.setToolTipText("yyyy-MM-dd");
        getContentPane().add(jTextFieldTo);
        jTextFieldTo.setBounds(110, 97, 150, 26);

        jLabelReason.setText("Reason:");
        getContentPane().add(jLabelReason);
        jLabelReason.setBounds(20, 140, 70, 16);

        jTextAreaReason.setColumns(20);
        jTextAreaReason.setRows(4);
        jTextAreaReason.setLineWrap(true);
        jTextAreaReason.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextAreaReason);
        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 162, 360, 100);

        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSubmit);
        jButtonSubmit.setBounds(20, 278, 100, 30);

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClose);
        jButtonClose.setBounds(140, 278, 100, 30);

        jLabelHint.setForeground(new java.awt.Color(80, 80, 80));
        jLabelHint.setText("Date format: yyyy-MM-dd  (e.g. 2025-07-01)");
        getContentPane().add(jLabelHint);
        jLabelHint.setBounds(20, 318, 360, 16);

        setSize(new java.awt.Dimension(410, 365));
    }// </editor-fold>//GEN-END:initComponents

    // ── Event Handlers ───────────────────────────────────────────────────────

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        if (currentEmployee == null) {
            JOptionPane.showMessageDialog(this, "No employee session found.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String fromStr = jTextFieldFrom.getText().trim();
        String toStr   = jTextFieldTo.getText().trim();
        String reason  = jTextAreaReason.getText().trim();

        if (fromStr.isEmpty() || toStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both From Date and To Date.", "Missing Fields", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (reason.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please provide a reason for the leave.", "Missing Reason", JOptionPane.WARNING_MESSAGE);
            return;
        }

        LocalDate fromDate, toDate;
        try {
            fromDate = LocalDate.parse(fromStr);
            toDate   = LocalDate.parse(toStr);
        } catch (DateTimeParseException ex) {
            JOptionPane.showMessageDialog(this, "Invalid date format. Use yyyy-MM-dd (e.g. 2025-07-01).", "Invalid Date", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (fromDate.isAfter(toDate)) {
            JOptionPane.showMessageDialog(this, "From Date must not be after To Date.", "Invalid Range", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            LeaveRequest req = leaveService.submit(currentEmployee.getEmpId(), fromDate, toDate, reason);
            JOptionPane.showMessageDialog(this,
                    "Leave request #" + req.getId() + " submitted successfully.\n"
                    + "Status: PENDING — awaiting HR/Manager review.",
                    "Submitted", JOptionPane.INFORMATION_MESSAGE);
            clearFields();
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Validation Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    // ── Helper methods ────────────────────────────────────────────────────────

    private void clearFields() {
        jTextFieldFrom.setText("");
        jTextFieldTo.setText("");
        jTextAreaReason.setText("");
    }

    // ── Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JLabel jLabelFrom;
    private javax.swing.JLabel jLabelHint;
    private javax.swing.JLabel jLabelReason;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaReason;
    private javax.swing.JTextField jTextFieldFrom;
    private javax.swing.JTextField jTextFieldTo;
    // End of variables declaration//GEN-END:variables
}
