package com.gui.Leave;

import com.motorph.model.Employee;
import com.motorph.model.LeaveRequest;
import com.motorph.service.LeaveService;
import com.motorph.util.AppContext;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * NetBeans GUI Builder form for HR / Manager / Admin to review and
 * approve or reject pending leave requests.
 *
 * Layout: defined in {@code LeaveApprovalForm.form} (do not edit the generated
 * code section).  All business logic lives in the event handlers and helper
 * methods below.
 */
public class LeaveApprovalForm extends javax.swing.JFrame {

    private final Employee currentEmployee;
    private final LeaveService leaveService;
    private static final DateTimeFormatter DISPLAY_FMT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

    // ── Constructors ─────────────────────────────────────────────────────────

    public LeaveApprovalForm() {
        this(AppContext.getInstance().getCurrentEmployee());
    }

    public LeaveApprovalForm(Employee reviewer) {
        this.currentEmployee = reviewer;
        this.leaveService    = AppContext.getInstance().getLeaveService();
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        loadPendingRequests();
    }

    // ── Generated Code ───────────────────────────────────────────────────────

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRequests = new javax.swing.JTable();
        jButtonRefresh = new javax.swing.JButton();
        jButtonApprove = new javax.swing.JButton();
        jButtonReject = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jLabelStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Leave Approval");
        getContentPane().setLayout(null);

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitle.setText("Leave Approval");
        getContentPane().add(jLabelTitle);
        jLabelTitle.setBounds(20, 15, 220, 30);

        jTableRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][] {},
            new String[] {"#", "Emp ID", "From", "To", "Reason", "Submitted"}
        ) {
            boolean[] canEdit = new boolean[] {false, false, false, false, false, false};
            public boolean isCellEditable(int rowIndex, int columnIndex) { return canEdit[columnIndex]; }
        });
        jTableRequests.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTableRequests);
        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 55, 760, 320);

        jButtonRefresh.setText("Refresh");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRefresh);
        jButtonRefresh.setBounds(20, 390, 100, 30);

        jButtonApprove.setBackground(new java.awt.Color(80, 180, 80));
        jButtonApprove.setText("Approve");
        jButtonApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApproveActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApprove);
        jButtonApprove.setBounds(140, 390, 100, 30);

        jButtonReject.setBackground(new java.awt.Color(220, 80, 80));
        jButtonReject.setText("Reject");
        jButtonReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRejectActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReject);
        jButtonReject.setBounds(260, 390, 100, 30);

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClose);
        jButtonClose.setBounds(680, 390, 100, 30);

        jLabelStatus.setText(" ");
        getContentPane().add(jLabelStatus);
        jLabelStatus.setBounds(20, 430, 760, 16);

        setSize(new java.awt.Dimension(810, 475));
    }// </editor-fold>//GEN-END:initComponents

    // ── Event Handlers ───────────────────────────────────────────────────────

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        loadPendingRequests();
        jLabelStatus.setText("Table refreshed.");
    }//GEN-LAST:event_jButtonRefreshActionPerformed

    private void jButtonApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApproveActionPerformed
        int selectedId = getSelectedRequestId();
        if (selectedId < 0) return;
        try {
            leaveService.approve(selectedId, currentEmployee.getEmpId());
            jLabelStatus.setText("Request #" + selectedId + " approved.");
            loadPendingRequests();
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonApproveActionPerformed

    private void jButtonRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRejectActionPerformed
        int selectedId = getSelectedRequestId();
        if (selectedId < 0) return;
        try {
            leaveService.reject(selectedId, currentEmployee.getEmpId());
            jLabelStatus.setText("Request #" + selectedId + " rejected.");
            loadPendingRequests();
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonRejectActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    // ── Helper methods ────────────────────────────────────────────────────────

    /** Populate the table with all currently pending requests. */
    private void loadPendingRequests() {
        DefaultTableModel model = (DefaultTableModel) jTableRequests.getModel();
        model.setRowCount(0);
        List<LeaveRequest> pending = leaveService.listPending();
        for (LeaveRequest req : pending) {
            model.addRow(new Object[]{
                req.getId(),
                req.getEmpId(),
                req.getFromDate().toString(),
                req.getToDate().toString(),
                req.getReason(),
                req.getSubmittedAt().format(DISPLAY_FMT)
            });
        }
        jLabelStatus.setText("Pending requests: " + pending.size());
    }

    /**
     * Get the request ID from the selected row, or show a warning and return -1.
     */
    private int getSelectedRequestId() {
        int row = jTableRequests.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Please select a leave request from the table.", "No Selection", JOptionPane.WARNING_MESSAGE);
            return -1;
        }
        return (Integer) jTableRequests.getValueAt(row, 0);
    }

    // ── Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApprove;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonReject;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRequests;
    // End of variables declaration//GEN-END:variables
}
